# Generated by Django 4.1.4 on 2022-12-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bookPurchased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookName", models.CharField(max_length=200)),
                ("authorName", models.CharField(max_length=200)),
                ("BookPrice", models.CharField(max_length=200)),
                ("Type", models.CharField(max_length=200)),
            ],
        ),
    ]
